### ISSUE TITLE
[Feature] Windows Terminal support

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Abhishek8394/lol-cat-py#2]
The new Windows Terminal has [support for colours](https://docs.microsoft.com/pl-pl/windows/terminal/images/powerline-powershell.png)

AFAIK, no other python packages that do this (lolcat) exist, so I'd really apreciate if this were worked on ༼ つ ◕_◕ ༽つ
![2021_05_06_00_59_36_Window](https://user-images.githubusercontent.com/46269721/117240125-ac211300-ae1f-11eb-8936-620035f5471f.jpg)

**Comment by Abhishek8394** [comment]
I will look in this, stay tuned!

**Comment by Abhishek8394** [comment]
I've published a `2.1.0` version with support for windows terminal. Thanks for bringing this to attention!
