### ISSUE TITLE
No support for colour on this terminal on my zsh that clearly supports color

### ISSUE THREAD

**Issue by osterchrisi** [Abhishek8394/lol-cat-py#4]
First of all thank you for sharing your code. I've been looking for this for quite a while until I found your python module. However when I run it within my code in my zsh, I get the above error for having no color support. but my zsh must have color support because it uses color all the time...

For testing I used the code from your example (1).

**Comment by Abhishek8394** [comment]
Can you show what error it is? Also how you're calling the command or
script.

**Comment by osterchrisi** [comment]
Error:
`No support for colour on this terminal. Try bash/cygwin.`

Code:
```
from lolpython import lol_py

text = "Lorem ipsum..."
lol_py(text)
```
I understand it tells me to use bash and I am using zsh. But I am thinking maybe the check for color could be coded differently so zsh passes as well, since it can totally do colors.

And simply for reference, this is what I actually want to achieve down the road:
```
from lolpython import lol_py
from pyfiglet import Figlet

f = Figlet(font='slant')
lol_py(print(f.renderText('My awesome welcome text')))
```
It'll basically be the equivalent of `figlet "My awesome welcome text" | lolcat` in terminal. If that will work, is yet another question :P

**Comment by Abhishek8394** [comment]
I've uploaded a new version to pip. Runs on my zsh, give it a shot and let me know if it worked.
Also it should be `| lolpython` instead of `| lolcat` 😉

**Comment by osterchrisi** [comment]
Amazing, works! Thank you so much for taking care of this. My life will be so colorful now :) `| lolpython` it will be!

**Comment by osterchrisi** [comment]
![Bildschirmfoto von 2021-11-14 10-47-02](https://user-images.githubusercontent.com/58528184/141675914-33a0d55a-2ca1-4914-9648-96aa03d3e57a.png)
